language: go

sudo: false

go:
  - tip

before_install:
  - go get github.com/golang/dep/...
  - go get github.com/mattn/goveralls

before_script:
  - dep ensure --vendor-only

script:
  - $HOME/gopath/bin/goveralls -service=travis-ci